spring.application.name=employeeAPI

# Puerto de la aplicación
#server.port=8080

# Core
spring.profiles.active=devh2

api-endpoint=/api/v1

logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql=trace

